import { afterEach, describe, expect, it, vi } from 'vitest';

const fetchTranscriptMock = vi.hoisted(() => vi.fn());
const listLanguagesMock = vi.hoisted(() => vi.fn());
vi.mock('youtube-transcript-plus', () => ({
  fetchTranscript: fetchTranscriptMock,
  listLanguages: listLanguagesMock,
}));

const { FreeTranscriptSource, ChainedTranscriptSource } =
  await import('./youtube-transcript-free.js');

afterEach(() => {
  fetchTranscriptMock.mockReset();
  listLanguagesMock.mockReset();
});

/** Default: an English auto track, so existing cases keep working. */
function offering(
  tracks = [{ languageCode: 'en', languageName: 'English', isAutoGenerated: true }],
) {
  listLanguagesMock.mockResolvedValue(tracks);
}

describe('FreeTranscriptSource', () => {
  it('joins the segments into one transcript', async () => {
    offering();
    fetchTranscriptMock.mockResolvedValue([{ text: 'We are no strangers' }, { text: 'to love' }]);

    // language now reflects the track actually requested, not null.
    expect(await new FreeTranscriptSource().fetch('abc')).toEqual({
      ok: true,
      text: 'We are no strangers to love',
      language: 'en',
    });
  });

  it('decodes the escaped entities the library leaves in', async () => {
    offering();
    // Measured: the library returns "We&#39;re" rather than "We're".
    fetchTranscriptMock.mockResolvedValue([{ text: 'We&#39;re no strangers &amp; more' }]);

    const result = await new FreeTranscriptSource().fetch('abc');
    expect(result).toMatchObject({ ok: true, text: "We're no strangers & more" });
  });

  /**
   * The load-bearing behaviour, and the reason this class exists rather than
   * the library being used directly.
   *
   * YouTube bot-walls this server per video. Measured on three: one served
   * caption tracks normally, two returned 1.1MB of HTML saying "Sign in to
   * confirm you're not a bot" with no tracks. The library cannot tell those
   * apart and reports BOTH as "No transcripts are available for the video".
   *
   * Passing that wording through would have the agent telling a student their
   * video has no transcript while YouTube is showing them one. So a failure
   * here is always service-unavailable, which lets the chain fall through.
   */
  it('never claims a video has no captions', async () => {
    offering();
    fetchTranscriptMock.mockRejectedValue(
      new Error('No transcripts are available for the video with ID "Lgq0KXYptLA"'),
    );

    expect(await new FreeTranscriptSource().fetch('Lgq0KXYptLA')).toEqual({
      ok: false,
      reason: 'service-unavailable',
    });
  });

  it('treats an empty transcript as a failure, not an empty video', async () => {
    offering();
    fetchTranscriptMock.mockResolvedValue([]);
    expect(await new FreeTranscriptSource().fetch('abc')).toEqual({
      ok: false,
      reason: 'service-unavailable',
    });
  });
});

describe('language selection', () => {
  /**
   * The defect this fixes. The library defaults to English, and most of this
   * account's teacher-posted videos are French -- so the default returned
   * "no transcript found" for videos that have perfectly good ones, and the
   * agent reported them as missing.
   *
   * Confirmed by running the equivalent Python library on a residential
   * machine: English-by-default failed on all four French videos, asking for
   * their real language returned every one.
   */
  it('asks for the language the video actually has', async () => {
    listLanguagesMock.mockResolvedValue([
      { languageCode: 'fr', languageName: 'French', isAutoGenerated: true },
    ]);
    fetchTranscriptMock.mockResolvedValue([{ text: 'le sel de voirie' }]);

    const result = await new FreeTranscriptSource().fetch('Lgq0KXYptLA');
    expect(fetchTranscriptMock).toHaveBeenCalledWith('Lgq0KXYptLA', { lang: 'fr' });
    expect(result).toMatchObject({ ok: true, language: 'fr' });
  });

  /** A human-written track beats speech recognition when both exist. */
  it('prefers a manual track over an auto-generated one', async () => {
    listLanguagesMock.mockResolvedValue([
      { languageCode: 'es', languageName: 'Spanish', isAutoGenerated: true },
      { languageCode: 'en', languageName: 'English', isAutoGenerated: false },
    ]);
    fetchTranscriptMock.mockResolvedValue([{ text: 'hello' }]);

    await new FreeTranscriptSource().fetch('abc');
    expect(fetchTranscriptMock).toHaveBeenCalledWith('abc', { lang: 'en' });
  });

  it('does not call fetch at all when the video offers nothing', async () => {
    listLanguagesMock.mockResolvedValue([]);

    expect(await new FreeTranscriptSource().fetch('abc')).toEqual({
      ok: false,
      reason: 'service-unavailable',
    });
    expect(fetchTranscriptMock).not.toHaveBeenCalled();
  });
});

describe('ChainedTranscriptSource', () => {
  const succeeds = { fetch: async () => ({ ok: true, text: 'got it', language: 'en' }) };
  const unavailable = { fetch: async () => ({ ok: false, reason: 'service-unavailable' }) };
  const noCaptions = { fetch: async () => ({ ok: false, reason: 'none-available' }) };

  it('falls through to the paid source when the free one is walled', async () => {
    const chain = new ChainedTranscriptSource([unavailable, succeeds] as never);
    expect(await chain.fetch('abc')).toMatchObject({ ok: true, text: 'got it' });
  });

  it('stops at the first success, so the paid credit is never spent', async () => {
    const paid = { fetch: vi.fn() };
    const chain = new ChainedTranscriptSource([succeeds, paid] as never);

    await chain.fetch('abc');
    expect(paid.fetch).not.toHaveBeenCalled();
  });

  /**
   * "No captions" is a fact about the video, not a failure of the source, so
   * asking a second service spends a credit to be told the same thing.
   */
  it('does not pay to re-confirm a video genuinely has no captions', async () => {
    const paid = { fetch: vi.fn() };
    const chain = new ChainedTranscriptSource([noCaptions, paid] as never);

    expect(await chain.fetch('abc')).toEqual({ ok: false, reason: 'none-available' });
    expect(paid.fetch).not.toHaveBeenCalled();
  });

  it('reports unavailable when every source is', async () => {
    const chain = new ChainedTranscriptSource([unavailable, unavailable] as never);
    expect(await chain.fetch('abc')).toEqual({ ok: false, reason: 'service-unavailable' });
  });
});
